# DXF export configuration file
# for Toml configuration format see https://toml.io/en/
# for regex testing see https://regex101.com/

[logging]
logging_level = "info" # debug, info, warning, error, critical

[paths]
logs = '\\hssieng\Jobs\DXF\logs'
part_files = '\\hssieng\Jobs'
name_strip_patterns = ["_mfg", "_copy"]  # patterns to strip from export names

[notes]
datetime_format = "%m-%d-%Y %I:%M:%S %p"
size_multiplier = 0.0125
offset = 10.0

[properties]
body_name_suffix = "_EXPORT_NAME"
empty_pattern = "^[ xX-]+$"  # regex pattern for empty property values
job = ["JobNo", "JOB_NUMBER"]
mark = ["Mark", "PIECE_MARK"]
drawing = ["DWG_NUMBER"]
material = ["MATERIALGRADE", "MATERIAL"]
spec = ["STEELSPEC"]
grade = ["STEELGRADE"]
test = ["STEELTEST"]

[layers.body]
layer = 1 # destination layer
single_body_name = "SN_PART" # if any body has this name, only that body will be exported
only_solid_bodies = true
exclude_body_names = ["SHIM", "(?:DO_NOT|NO|SKIP)_EXPORT"] # body names to exclude from export

[layers.marking]
layer = 2 # destination layer
sketches = ["ZINC", "HEATNUM", "MARKING"] # sketch names or regex patterns

[layers.no_cut]
layer = 3 # destination layer
sketches = ["NO[-_]?CUT"] # sketch names or regex patterns

[layers.detail]
layer = 4 # destination layer
sketches = ["DETAIL"] # sketch names or regex patterns