[package]
name = "filedialog"
version = "0.1.0"
edition = "2018"

[lib]
name = "filedialog"
crate-type = ["cdylib"]

[dependencies]
native-windows-gui = "1.0.11"
native-windows-derive = "1.0.5"

[dependencies.pyo3]
version = "0.21.1"
features = ["extension-module"]
